import { SlideData } from 'types';

export const slideData: SlideData[] = [
  {
    name: 'Apocalypses',
    info: 'Watercolor on paper',
    year: 2021,
    size: '29.5" x 41.5"',
    key: 'apocalypses',
  },
  {
    name: 'Doctor`s Hands',
    info: 'Watercolor on paper',
    year: 2021,
    size: '27.5" x 39.5"',
    key: 'doctorsHands',
  },
  {
    name: 'Fireflies',
    info: 'Watercolor on paper',
    year: 2021,
    size: '29.5" x 41.5"',
    key: 'fireFlies',
  },
  {
    name: 'For Life',
    info: 'Watercolor on paper',
    year: 2020,
    size: '29.5" x 41.5"',
    key: 'forLife',
  },
  {
    name: 'Hiroshima',
    info: 'Watercolor on paper',
    year: 2021,
    size: '29.5" x 41.5"',
    key: 'hiroshima',
  },
  {
    name: 'Infinity',
    info: 'Watercolor on paper',
    year: 2021,
    size: '29.5" x 41.5"',
    key: 'infinity',
  },
  {
    name: 'Krtsanisy Poppies',
    info: 'Watercolor on paper',
    year: 2021,
    size: '29.5" x 41.5"',
    key: 'krtsanisyPoppies',
  },
  {
    name: 'Lake of Tranquility',
    info: 'Watercolor on paper',
    year: 2021,
    size: '27.5" x 39.5"',
    key: 'lakeOfTranquility',
  },
  {
    name: 'My Yellow',
    info: 'Watercolor on paper',
    year: 2021,
    size: '27.5" x 39.5"',
    key: 'myYellow',
  },
  {
    name: 'Night on Earth',
    info: 'Watercolor on paper',
    year: 2020,
    size: '29.5" x 41.5"',
    key: 'nightOnEarth',
  },
  {
    name: 'Nurse',
    info: 'Watercolor on paper',
    year: 2020,
    size: '29.5" x 41.5"',
    key: 'nurse',
  },
  {
    name: 'Paradise Apple Tree',
    info: 'Watercolor on paper',
    year: 2015,
    size: '41.5" x 29.5"',
    key: 'paradiseAppleTree',
  },
  {
    name: 'Rain',
    info: 'Watercolor on paper',
    year: 2020,
    size: '29.5" x 41.5"',
    key: 'rain',
  },
  {
    name: 'Spring',
    info: 'Watercolor on paper',
    year: 2021,
    size: '27.5" x 39.5"',
    key: 'spring',
  },
  {
    name: 'Summer',
    info: 'Watercolor on paper',
    year: 2021,
    size: '27.5" x 39.5"',
    key: 'summer',
  },
  {
    name: 'Sunset',
    info: 'Watercolor on paper',
    year: 2021,
    size: '27.5" x 39.5"',
    key: 'sunset',
  },
];
